// Package main is `slink-public-server`.
//
// `slink-public-server` is intended to be public facing, serving the
// lookup+redirect requests for IDs generated by this service, e.g. if there's a
// `ShortLink{ID: 123abc, LinkURL: https://github.com}`, then a request to
// `https://example.com/123abc` will redirect to `https://github.com`.
//
// There are no other APIs available on this server. See `slink-admin-server`
// for other APIs.
package main
